# Generated by Django 4.2.16 on 2025-07-29 10:35

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_created_at_alter_agent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Agent name, can be generated automatically.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="urls",
            field=models.CharField(
                blank=True,
                help_text="Agent URL",
                null=True,
                validators=[api.validators.validate_url],
            ),
        ),
    ]
